### PR TITLE
Update actions for OpsGenie v2

### LINKED ISSUE #3: Migrate to new Python module
A user on Slack (`@morph42`) reported an error when using this pack:

`ValueError: HTTP error: 410: '{"code":32,"error":"DeprecatedApiException[API v1 is deprecated. Please refer https://docs.opsgenie.com/docs/dashboard/rest-api for details of the new version]"}'`

It appears OpsGenie has deprecated v1 of their API https://docs.opsgenie.com/docs/web-api

However instead of actually deprecating it seems they return 400 errors.

The python module this pack relies on has an issue created to regenerate based on the new swagger  spec (https://github.com/opsgenie/opsgenie-python-sdk/issues/9). There is no current PR available.

An external user has created a fork with the most up-to-date swagger bindings called `opsgenie_swagger`  https://github.com/criteo-forks/opsgenie-python-sdk   

https://pypi.org/project/opsgenie_swagger/0.3.2/

### PR DESCRIPTION
**Pull request by MeralBusraTekinsen**
Actions are updated for Opsgenie v2 APIs. Also action tests are implemented for v2. Can you please review it?

Fixes #3

### CODE REVIEW

**Comment by LindsayHill** [comment]
Thanks for the PR - much appreciated. Looks like it needs some linting fixes? I recommend running a linter locally, because the CircleCI checks fail at the first file with linting errors. Faster to run & fix all checks locally in one go

**Comment by LindsayHill** [comment]
Like I said, it's easier to run flake8/pylint locally, so you can see all the errors at once, rather than on a per-file basis.

**Comment by MeralBusraTekinsen** [comment]
Thanks for advice.

**Comment by LindsayHill** [comment]
Looking good. Can you please update the version in pack.yaml, and add an entry to CHANGES.md? Then I’ll merge it.

**Comment by LindsayHill** [comment]
Thanks so much for this!

**Comment by MeralBusraTekinsen** [comment]
Also, I want to say that some of actions in v1 removed from v2 like send_heartbeat. You may want to update README file too i think.

**Pull request merged**
